from flask import Flask, jsonify, request
app = Flask(__name__)

country_list = {
'Afghanistan': 'Kabul',
'Albania': 'Tirana',
'Algeria': 'Algiers',
'American Samoa': 'Pago Pago',
'Andorra': 'Andorra la Vella',
'Angola': 'Luanda',
'Anguilla': 'The Valley',
'Antarctica': '',
'Antigua and Barbuda': 'St. John\'s',
'Argentina': 'Buenos Aires',
'Armenia': 'Yerevan',
'Aruba': 'Oranjestad',
'Australia': 'Canberra',
'Austria': 'Vienna',
'Azerbaijan': 'Baku',
'Bahamas': 'Nassau',
'Bahrain': 'Manama',
'Bangladesh': 'Dhaka',
'Barbados': 'Bridgetown',
'Belarus': 'Minsk',
'Belgium': 'Brussels',
'Belize': 'Belmopan',
'Benin': 'Porto-Novo',
'Bermuda': 'Hamilton',
'Bhutan': 'Thimphu',
'Bolivia': 'Sucre',
'Bonaire': 'Kralendijk',
'Bosnia and Herzegovina': 'Sarajevo',
'Botswana': 'Gaborone',
'Bouvet Island': ' ',
'Brazil': 'Brasilia',
'British Indian Ocean Territory': '',
'British Virgin Islands': 'Road Town',
'Brunei': 'Bandar Seri Begawan',
'Bulgaria': 'Sofia',
'Burkina Faso': 'Ouagadougou',
'Burundi': 'Bujumbura',
'Cambodia': 'Phnom Penh',
'Cameroon': 'Yaounde',
'Canada': 'Ottawa',
'Cape Verde': 'Praia',
'Cayman Islands': 'George Town',
'Central African Republic': 'Bangui',
'Chad': 'N\'Djamena',
'Chile': 'Santiago',
'China': 'Beijing',
'Christmas Island': 'Flying Fish Cove',
'Cocos [Keeling] Islands': 'West Island',
'Colombia': 'Bogota',
'Comoros': 'Moroni',
'Cook Islands': 'Avarua',
'Costa Rica': 'San Jose',
'Croatia': 'Zagreb',
'Cuba': 'Havana',
'Curacao': 'Willemstad',
'Cyprus': 'Nicosia',
'Czechia': 'Prague',
'Democratic Republic of the Congo': 'Kinshasa',
'Denmark': 'Copenhagen',
'Djibouti': 'Djibouti',
'Dominica': 'Roseau',
'Dominican Republic': 'Santo Domingo',
'East Timor': 'Dili',
'Ecuador': 'Quito',
'Egypt': 'Cairo',
'El Salvador': 'San Salvador',
'Equatorial Guinea': 'Malabo',
'Eritrea': 'Asmara',
'Estonia': 'Tallinn',
'Ethiopia': 'Addis Ababa',
'Falkland Islands': 'Stanley',
'Faroe Islands': 'Torshavn',
'Fiji': 'Suva',
'Finland': 'Helsinki',
'France': 'Paris',
'French Guiana': 'Cayenne',
'French Polynesia': 'Papeete',
'French Southern Territories': 'Port-aux-Francais',
'Gabon': 'Libreville',
'Gambia': 'Bathurst',
'Georgia': 'Tbilisi',
'Germany': 'Berlin',
'Ghana': 'Accra',
'Gibraltar': 'Gibraltar',
'Greece': 'Athens',
'Greenland': 'Nuuk',
'Grenada': 'St. George\'s',
'Guadeloupe': 'Basse-Terre',
'Guam': 'Hagatna',
'Guatemala': 'Guatemala City',
'Guernsey': 'St Peter Port',
'Guinea': 'Conakry',
'Guinea-Bissau': 'Bissau',
'Guyana': 'Georgetown',
'Haiti': 'Port-au-Prince',
'Heard Island and McDonald Islands': '',
'Honduras': 'Tegucigalpa',
'Hong Kong': 'Hong Kong',
'Hungary': 'Budapest',
'Iceland': 'Reykjavik',
'India': 'New Delhi',
'Indonesia': 'Jakarta',
'Iran': 'Tehran',
'Iraq': 'Baghdad',
'Ireland': 'Dublin',
'Isle of Man': 'Douglas',
'Israel': '',
'Italy': 'Rome',
'Ivory Coast': 'Yamoussoukro',
'Jamaica': 'Kingston',
'Japan': 'Tokyo',
'Jersey': 'Saint Helier',
'Jordan': 'Amman',
'Kazakhstan': 'Astana',
'Kenya': 'Nairobi',
'Kiribati': 'Tarawa',
'Kosovo': 'Pristina',
'Kuwait': 'Kuwait City',
'Kyrgyzstan': 'Bishkek',
'Laos': 'Vientiane',
'Latvia': 'Riga',
'Lebanon': 'Beirut',
'Lesotho': 'Maseru',
'Liberia': 'Monrovia',
'Libya': 'Tripoli',
'Liechtenstein': 'Vaduz',
'Lithuania': 'Vilnius',
'Luxembourg': 'Luxembourg',
'Macao': 'Macao',
'Macedonia': 'Skopje',
'Madagascar': 'Antananarivo',
'Malawi': 'Lilongwe',
'Malaysia': 'Kuala Lumpur',
'Maldives': 'Male',
'Mali': 'Bamako',
'Malta': 'Valletta',
'Marshall Islands': 'Majuro',
'Martinique': 'Fort-de-France',
'Mauritania': 'Nouakchott',
'Mauritius': 'Port Louis',
'Mayotte': 'Mamoudzou',
'Mexico': 'Mexico City',
'Micronesia': 'Palikir',
'Moldova': 'Chisinau',
'Monaco': 'Monaco',
'Mongolia': 'Ulan Bator',
'Montenegro': 'Podgorica',
'Montserrat': 'Plymouth',
'Morocco': 'Rabat',
'Mozambique': 'Maputo',
'Myanmar [Burma]': 'Naypyitaw',
'Namibia': 'Windhoek',
'Nauru': 'Yaren',
'Nepal': 'Kathmandu',
'Netherlands': 'Amsterdam',
'New Caledonia': 'Noumea',
'New Zealand': 'Wellington',
'Nicaragua': 'Managua',
'Niger': 'Niamey',
'Nigeria': 'Abuja',
'Niue': 'Alofi',
'Norfolk Island': 'Kingston',
'North Korea': 'Pyongyang',
'Northern Mariana Islands': 'Saipan',
'Norway': 'Oslo',
'Oman': 'Muscat',
'Pakistan': 'Islamabad',
'Palau': 'Melekeok',
'Palestine': '',
'Panama': 'Panama City',
'Papua New Guinea': 'Port Moresby',
'Paraguay': 'Asuncion',
'Peru': 'Lima',
'Philippines': 'Manila',
'Pitcairn Islands': 'Adamstown',
'Poland': 'Warsaw',
'Portugal': 'Lisbon',
'Puerto Rico': 'San Juan',
'Qatar': 'Doha',
'Republic of the Congo': 'Brazzaville',
'Romania': 'Bucharest',
'Russia': 'Moscow',
'Rwanda': 'Kigali',
'Reunion': 'Saint-Denis',
'Saint Barthelemy': 'Gustavia',
'Saint Helena': 'Jamestown',
'Saint Kitts and Nevis': 'Basseterre',
'Saint Lucia': 'Castries',
'Saint Martin': 'Marigot',
'Saint Pierre and Miquelon': 'Saint-Pierre',
'Saint Vincent and the Grenadines': 'Kingstown',
'Samoa': 'Apia',
'San Marino': 'San Marino',
'Saudi Arabia': 'Riyadh',
'Senegal': 'Dakar',
'Serbia': 'Belgrade',
'Seychelles': 'Victoria',
'Sierra Leone': 'Freetown',
'Singapore': 'Singapore',
'Sint Maarten': 'Philipsburg',
'Slovakia': 'Bratislava',
'Slovenia': 'Ljubljana',
'Solomon Islands': 'Honiara',
'Somalia': 'Mogadishu',
'South Africa': 'Pretoria',
'South Georgia and the South Sandwich Islands': 'Grytviken',
'South Korea': 'Seoul',
'South Sudan': 'Juba',
'Spain': 'Madrid',
'Sri Lanka': 'Colombo',
'Sudan': 'Khartoum',
'Suriname': 'Paramaribo',
'Svalbard and Jan Mayen': 'Longyearbyen',
'Swaziland': 'Mbabane',
'Sweden': 'Stockholm',
'Switzerland': 'Bern',
'Syria': 'Damascus',
'Sao Tome and Principe': 'Sao Tome',
'Taiwan': 'Taipei',
'Tajikistan': 'Dushanbe',
'Tanzania': 'Dodoma',
'Thailand': 'Bangkok',
'Togo': 'Lome',
'Tokelau': '',
'Tonga': 'Nuku\'alofa',
'Trinidad and Tobago': 'Port of Spain',
'Tunisia': 'Tunis',
'Turkey': 'Ankara',
'Turkmenistan': 'Ashgabat',
'Turks and Caicos Islands': 'Cockburn Town',
'Tuvalu': 'Funafuti',
'U.S. Minor Outlying Islands': '',
'U.S. Virgin Islands': 'Charlotte Amalie',
'Uganda': 'Kampala',
'Ukraine': 'Kiev',
'United Arab Emirates': 'Abu Dhabi',
'United Kingdom': 'London',
'United States': 'Washington',
'Uruguay': 'Montevideo',
'Uzbekistan': 'Tashkent',
'Vanuatu': 'Port Vila',
'Vatican City': 'Vatican City',
'Venezuela': 'Caracas',
'Vietnam': 'Hanoi',
'Wallis and Futuna': 'Mata-Utu',
'Western Sahara': 'Laayoune / El Aaiun',
'Yemen': 'Sanaa',
'Zambia': 'Lusaka',
'Zimbabwe': 'Harare',
'Aland': 'Mariehamn'
}

#country_list = {"BD": "Dhaka", "BE": "Brussels", "BF": "Ouagadougou", "BG": "Sofia", "BA": "Sarajevo", "BB": "Bridgetown", "WF": "Mata Utu", "BL": "Gustavia", "BM": "Hamilton", "BN": "Bandar Seri Begawan", "BO": "Sucre", "BH": "Manama", "BI": "Bujumbura", "BJ": "Porto-Novo", "BT": "Thimphu", "JM": "Kingston", "BV": "", "BW": "Gaborone", "WS": "Apia", "BQ": "", "BR": "Brasilia", "BS": "Nassau", "JE": "Saint Helier", "BY": "Minsk", "BZ": "Belmopan", "RU": "Moscow", "RW": "Kigali", "RS": "Belgrade", "TL": "Dili", "RE": "Saint-Denis", "TM": "Ashgabat", "TJ": "Dushanbe", "RO": "Bucharest", "TK": "", "GW": "Bissau", "GU": "Hagatna", "GT": "Guatemala City", "GS": "Grytviken", "GR": "Athens", "GQ": "Malabo", "GP": "Basse-Terre", "JP": "Tokyo", "GY": "Georgetown", "GG": "St Peter Port", "GF": "Cayenne", "GE": "Tbilisi", "GD": "St. George's", "GB": "London", "GA": "Libreville", "SV": "San Salvador", "GN": "Conakry", "GM": "Banjul", "GL": "Nuuk", "GI": "Gibraltar", "GH": "Accra", "OM": "Muscat", "TN": "Tunis", "JO": "Amman", "HR": "Zagreb", "HT": "Port-au-Prince", "HU": "Budapest", "HK": "Hong Kong", "HN": "Tegucigalpa", "HM": "", "VE": "Caracas", "PR": "San Juan", "PS": "East Jerusalem", "PW": "Melekeok", "PT": "Lisbon", "SJ": "Longyearbyen", "PY": "Asuncion", "IQ": "Baghdad", "PA": "Panama City", "PF": "Papeete", "PG": "Port Moresby", "PE": "Lima", "PK": "Islamabad", "PH": "Manila", "PN": "Adamstown", "PL": "Warsaw", "PM": "Saint-Pierre", "ZM": "Lusaka", "EH": "El-Aaiun", "EE": "Tallinn", "EG": "Cairo", "ZA": "Pretoria", "EC": "Quito", "IT": "Rome", "VN": "Hanoi", "SB": "Honiara", "ET": "Addis Ababa", "SO": "Mogadishu", "ZW": "Harare", "SA": "Riyadh", "ES": "Madrid", "ER": "Asmara", "ME": "Podgorica", "MD": "Chisinau", "MG": "Antananarivo", "MF": "Marigot", "MA": "Rabat", "MC": "Monaco", "UZ": "Tashkent", "MM": "Nay Pyi Taw", "ML": "Bamako", "MO": "Macao", "MN": "Ulan Bator", "MH": "Majuro", "MK": "Skopje", "MU": "Port Louis", "MT": "Valletta", "MW": "Lilongwe", "MV": "Male", "MQ": "Fort-de-France", "MP": "Saipan", "MS": "Plymouth", "MR": "Nouakchott", "IM": "Douglas, Isle of Man", "UG": "Kampala", "TZ": "Dodoma", "MY": "Kuala Lumpur", "MX": "Mexico City", "IL": "Jerusalem", "FR": "Paris", "IO": "Diego Garcia", "SH": "Jamestown", "FI": "Helsinki", "FJ": "Suva", "FK": "Stanley", "FM": "Palikir", "FO": "Torshavn", "NI": "Managua", "NL": "Amsterdam", "NO": "Oslo", "NA": "Windhoek", "VU": "Port Vila", "NC": "Noumea", "NE": "Niamey", "NF": "Kingston", "NG": "Abuja", "NZ": "Wellington", "NP": "Kathmandu", "NR": "Yaren", "NU": "Alofi", "CK": "Avarua", "XK": "Pristina", "CI": "Yamoussoukro", "CH": "Berne", "CO": "Bogota", "CN": "Beijing", "CM": "Yaounde", "CL": "Santiago", "CC": "West Island", "CA": "Ottawa", "CG": "Brazzaville", "CF": "Bangui", "CD": "Kinshasa", "CZ": "Prague", "CY": "Nicosia", "CX": "Flying Fish Cove", "CR": "San Jose", "CW": " Willemstad", "CV": "Praia", "CU": "Havana", "SZ": "Mbabane", "SY": "Damascus", "SX": "Philipsburg", "KG": "Bishkek", "KE": "Nairobi", "SS": "Juba", "SR": "Paramaribo", "KI": "Tarawa", "KH": "Phnom Penh", "KN": "Basseterre", "KM": "Moroni", "ST": "Sao Tome", "SK": "Bratislava", "KR": "Seoul", "SI": "Ljubljana", "KP": "Pyongyang", "KW": "Kuwait City", "SN": "Dakar", "SM": "San Marino", "SL": "Freetown", "SC": "Victoria", "KZ": "Astana", "KY": "George Town", "SG": "Singapur", "SE": "Stockholm", "SD": "Khartoum", "DO": "Santo Domingo", "DM": "Roseau", "DJ": "Djibouti", "DK": "Copenhagen", "VG": "Road Town", "DE": "Berlin", "YE": "Sanaa", "DZ": "Algiers", "US": "Washington", "UY": "Montevideo", "YT": "Mamoudzou", "UM": "", "LB": "Beirut", "LC": "Castries", "LA": "Vientiane", "TV": "Funafuti", "TW": "Taipei", "TT": "Port of Spain", "TR": "Ankara", "LK": "Colombo", "LI": "Vaduz", "LV": "Riga", "TO": "Nuku'alofa", "LT": "Vilnius", "LU": "Luxembourg", "LR": "Monrovia", "LS": "Maseru", "TH": "Bangkok", "TF": "Port-aux-Francais", "TG": "Lome", "TD": "N'Djamena", "TC": "Cockburn Town", "LY": "Tripolis", "VA": "Vatican City", "VC": "Kingstown", "AE": "Abu Dhabi", "AD": "Andorra la Vella", "AG": "St. John's", "AF": "Kabul", "AI": "The Valley", "VI": "Charlotte Amalie", "IS": "Reykjavik", "IR": "Tehran", "AM": "Yerevan", "AL": "Tirana", "AO": "Luanda", "AQ": "", "AS": "Pago Pago", "AR": "Buenos Aires", "AU": "Canberra", "AT": "Vienna", "AW": "Oranjestad", "IN": "New Delhi", "AX": "Mariehamn", "AZ": "Baku", "IE": "Dublin", "ID": "Jakarta", "UA": "Kiev", "QA": "Doha", "MZ": "Maputo"}

      

@app.route('/', methods=['GET'])
def test():
    return '<h1>Welcome to Country-capital</h1>\n<p>This application is built on the Python Flask framework and is the focus for finding captial for respective country!</p>'

@app.route('/apex/', methods = ['GET'])
def show():
    return jsonify({'Capitals':country_list})

@app.route('/apex/<string:country>', methods = ['GET'])
def find(country):
    if country in country_list:
        return country_list[country]
    else:
        return "no record found"


if __name__ == '__main__':
    app.run(debug=True,port=8080)